#
# ESLint Configuration (YAML-Formatting)
#
env:     {es6: true, jest: true, node: true}
extends: airbnb-base
parser:  babel-eslint
plugins: ['import']
root:    true
rules:
  global-require:                    0
  import/no-extraneous-dependencies: [2, {devDependencies: ['__tests__/**']}]
  import/prefer-default-export:      0
  key-spacing:                       0
  no-console:                        [2, {allow: ['dir', 'error', 'info', 'warn']}]
  no-multi-spaces:                   0
  no-param-reassign:                 0
  no-use-before-define:              0
  semi:                              [2, 'never']
