service:          ${file(package.json):name}

frameworkVersion: ">=1.25.0 <2.0.0"

plugins:
  - serverless-plugin-webpack
  - serverless-aws-documentation
  - serverless-domain-manager
  - serverless-offline

package:
  individually:           true # package each lambda function individually
  excludeDevDependencies: false # we lean on webpack do the tree-shaking
  exclude:                ['node_modules/**/aws-sdk/**']

custom:
  ${file(build/config/custom.yml)}

provider:
  name:       "aws"
  memorySize: 1024
  timeout:    30
  deploymentBucket:
    serverSideEncryption: AES256
  # runtime:                ${self:custom.service.RUNTIME}
  # stage:                  ${self:custom.service.STAGE}
  # region:                 ${self:custom.service.REGION}
  # stackTags:              ${self:custom.stackTags}
  # environment:            ${file(build/config/custom.yml):environmentVariables}
  #   # <:                    ${file(build/config/custom.yml):environmentVariables}
  #   # NODE_ENV:             ${self:custom.service.STAGE}
  # iamRoleStatements:      ${file(build/config/iam_role_statements.yml)}

# functions: ${file(build/config/functions.yml)}

# resources: ${file(build/config/resources.yml)}
