# provider:
#   # if set, the values below will override those set within `02-boilerplate.yml`
#   memorySize: 512
#   timeout:    6
#
custom:

  iamRoleStatements:
    - Effect: Allow
      Action:
        # - dynamodb:DeleteItem # off by default, because you likely lack iam permissions anyhow
        - dynamodb:DescribeTable
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-benefits*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-carrier-application*
        # above is an example of how we should refactor the line below, which calls `prod` table directly
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-cart*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-employee-documents*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-persons*
        - arn:aws:dynamodb:us-west-2:409076796536:table/prod-carrier-application*  # at present, and because we haven't transfered over the templates, the data store for HIOS->to->docusignTemplateId is in prod only
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-west-2:409076796536:function:get-filled-pdf-application:${self:custom.service.STAGE}
        - arn:aws:lambda:us-west-2:409076796536:function:get-ssn:${self:custom.service.STAGE}
