# provider:
#   # if set, the values below will override those set within `02-boilerplate.yml`
#   memorySize: 512
#   timeout:    6
#
custom:

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        # - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-benefits*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-carrier-application-documents*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-carrier-application-hios*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-carrier-application*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-carrier-applications*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-cart*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-employee-documents*
        - arn:aws:dynamodb:us-west-2:409076796536:table/${self:custom.service.STAGE}-persons*
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-west-2:409076796536:function:get-filled-pdf-application:${self:custom.service.STAGE}
        - arn:aws:lambda:us-west-2:409076796536:function:get-ssn:${self:custom.service.STAGE}
