functions:
  ping:
    description: ${self:custom.documentation.summary} | Ping / Pong
    handler: build/routes/ping/index.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
          documentation:
            summary: 'ping'
            description: Service Up? Check w/ Ping / Pong!

  createEnvelope:
    description: ${self:custom.documentation.summary} | Create Envelope [POST]
    handler: build/routes/envelope/index.createEnvelope
    events:
      - http:
          path: envelope
          method: post
          cors: true
          documentation:
            summary: Create Envelope (on DocuSign)
            description: Create Envelope (on DocuSign) [POST]
            requestBody:
              description: "Request body description"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "Response body description"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
            requestModels:
              "application/json": "CreateEnvelope"

  getEnvelope:
    description: ${self:custom.documentation.summary} | Get Envelope [GET]
    handler: build/routes/envelope/index.getEnvelope
    events:
      - http:
          path: envelope/{envelopeId}
          method: get
          request:
            parameters:
              paths:
                envelopeId: true
          cors: true
          documentation:
            summary: Get Envelope (from DocuSign)
            description: Get Envelope (from DocuSign) [GET]
            requestBody:
              description: "Request body description"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "Response body description"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
            requestModels:
              "application/json": "GetEnvelope"

  createSigningSession:
    description: ${self:custom.documentation.summary} | Create Signing Session [POST]
    handler: build/routes/envelope/sign/index.createSigningSession
    events:
      - http:
          path: envelope/{envelopeId}/sign
          method: post
          request:
            parameters:
              paths:
                envelopeId: true
          cors: true
          documentation:
            summary: Create Signing Session (from DocuSign)
            description: Create Signing Session (from DocuSign) [GET]
            requestBody:
              description: "Request body description"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "Response body description"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
            requestModels:
              "application/json": "CreateSigningSession"


    # getApplication:
    #   description: ${self:custom.documentation.summary} | Get Application [GET]
    #   handler: build/routes/index.getApplication
    #   events:
    #     - http:
    #         path: {applicationId}
    #         method: get
    #         request:
    #           parameters:
    #             paths:
    #               applicationId: true
    #         cors: true
    #         documentation:
    #           summary: Get Application
    #           description: Get Application [GET]
