functions:
  ping:
    description: ${self:custom.documentation.summary} | Ping / Pong
    handler: build/routes/ping/index.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
          documentation:
            summary: 'ping'
            description: Service Up? Check w/ Ping / Pong!

  createEnvelope:
    description: ${self:custom.documentation.summary} | Create Envelope [POST]
    handler: build/routes/envelope/index.createEnvelope
    events:
      - http:
          path: envelope
          method: post
          cors: true
          documentation:
            summary: Create Envelope (on DocuSign)
            description: Create Envelope (on DocuSign) [POST]
            requestBody:
              description: "Request body description"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "Response body description"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
            requestModels:
              "application/json": "CreateEnvelope"

  getEnvelope:
    description: ${self:custom.documentation.summary} | Get Envelope [GET]
    handler: build/routes/envelope/index.getEnvelope
    events:
      - http:
          path: envelope/{envelopeId}
          method: get
          request:
            parameters:
              paths:
                envelopeId: true
          cors: true
          documentation:
            summary: Get Envelope (from DocuSign)
            description: Get Envelope (from DocuSign) [GET]
            requestBody:
              description: "Request body description"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "Response body description"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
            requestModels:
              "application/json": "GetEnvelope"

  createSigningSession:
    description: ${self:custom.documentation.summary} | Create Signing Session [POST]
    handler: build/routes/envelope/sign/index.createSigningSession
    events:
      - http:
          path: envelope/{envelopeId}/sign
          method: post
          request:
            parameters:
              paths:
                envelopeId: true
          cors: true
          documentation:
            summary: Create Signing Session (from DocuSign)
            description: Create Signing Session (from DocuSign) [GET]
            requestBody:
              description: "Request body description"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "Response body description"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
            requestModels:
              "application/json": "CreateSigningSession"

  getCartWithApplicationStatus:
    description: ${self:custom.documentation.summary} | Get Cart With Application Status [GET]
    handler: build/routes/status/index.getCartWithApplicationStatus
    events:
      - http:
          path: status
          method: get
          cors: true
          documentation:
            summary: Get Cart With Application Status
            description: Get Cart With Application Status [GET]
            requestBody:
              description: "Request body description"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "Response body description"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
            requestModels:
              "application/json": "GetCartWithApplicationStatus"
