functions:
  ping:
    description: Ping / Pong
    handler: build/routes/ping/index.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
          documentation:
            summary: 'ping'
            description: Service Up? Check w/ Ping / Pong!

  createEnvelope:
    handler: build/routes/sign/envelope/index.createEnvelope
    events:
      - http:
          path: sign/envelope
          method: post
          cors: true
          documentation:
            summary: Create Envelope
            description: Create Envelope [POST]
            tags: ["docusign", "sign", "envelope", "signing session"]
            requestBody:
              description: "Request body description"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "Response body description"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
            requestModels:
              "application/json": "CreateEnvelope"

# **********************************************************
# DON'T WORRY ABOUT THE BELOW CURRENTLY-DISABLED-ENDPOINTS *
# **********************************************************

  # createSigningSession:
  #   handler: build/routes/sign/session/index.createSigningSession
  #   events:
  #     - http:
  #         # path: sign/{applicationId}/session # ?
  #         path: sign/envelope/{envelopeId}/session
  #         method: post
  #         request:
  #           parameters:
  #             paths:
  #               envelopeId: true
  #         cors: true
  #         documentation:
  #           summary: Create Signing Session
  #           description: Create Signing Session [POST]

  # getSigningSession:
  #   handler: build/routes/sign/session/index.getSigningSession
  #   events:
  #     - http:
  #         # path: sign/{applicationId}/session # ?
  #         path: sign/envelope/{envelopeId}/session
  #         method: get
  #         request:
  #           parameters:
  #             paths:
  #               envelopeId: true
  #         cors: true
  #         documentation:
  #           summary: Get Signing Session
  #           description: Get Signing Session [POST]

  # getApplication:
  #   handler: build/routes/cart/index.get
  #   events:
  #     - http:
  #         path: sign/cart/{cartID}/applications  // fetch all applications from a cart?
  #         method: get
  #         cors: true
  #         documentation:
  #           summary: Get Application
  #           description: Get Application [GET]

# calling this `fetch`, because it's via `POST`-http-method, not `GET`
  # fetchCart:
  #   handler: build/routes/cart/index.fetchCart
  #   events:
  #     - http:
  #         path: cart
  #         method: post
  #         cors: true
  #         documentation:
  #           summary: Fetch Cart
  #           description: Fetch Cart (& Application / Status) [POST]
