functions:
  ping:
    description: Ping / Pong
    handler: build/routes/ping/index.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
          documentation:
            summary: 'ping'
            description: Service Up? Check w/ Ping / Pong!

  createEnvelope:
    handler: build/routes/envelope/index.create
    events:
      - http:
          path: envelope
          method: post
          cors: true
          documentation:
            summary: Create Envelope
            description: Create Envelope [POST]

  # getApplication:
  #   handler: build/routes/index.get
  #   events:
  #     - http:
  #         path: /cart/{cartID}/applications  // fetch all applications from a cart?
  #         path: /                            // fetch one application ? (remember: service is named 'application')
  #         method: get
  #         cors: true
  #         documentation:
  #           summary: Get Application
  #           description: Get Application [GET]

# calling this `fetch`, because it's via `POST`-http-method, not `GET`
  fetchCart:
    handler: build/routes/cart/index.fetchCart
    events:
      - http:
          path: cart
          method: post
          cors: true
          documentation:
            summary: Fetch Cart
            description: Fetch Cart (& Application / Status) [POST]
