service:
  NAME:         ${file(package.json):name, 'untitled-project'}
  STAGE:        ${opt:stage, env:NODE_ENV, file(package.json):config.stage, 'int'}
  REGION:       ${opt:region, file(package.json):config.region, 'us-west-2'}
  RUNTIME:      ${file(package.json):config.runtime, 'nodejs6.10'}
  VERSION:      ${file(package.json):version}
  DESCRIPTION:  ${file(package.json):description}

documentation:
  description:  Hixme API | ${file(package.json):description}
  summary:      ${file(package.json):description}
  version:      ${file(package.json):version}
  models:       ${file(schemas/all.yml)}
  # authorizers:  ${file(schemas/authorizers.yml)}
  resources:    ${file(schemas/resources.yml)}

customDomain:
  basePath:             ${file(env.js):getAPIBasePath}
  certificateName:      '*.hixme.com'
  createRoute53Record:  false # leave as-is, unless you know what you're doing
  domainName:           ${file(env.js):getHostname}
  stage:                ${file(env.js):getDesiredStageFromPackageJSON}

serverless-offline:
  prefix: ${file(env.js):getAPIBasePath}
